### ISSUE TITLE
Compilation fails under C++17

### ISSUE THREAD

**Issue by petrmanek** [EPC-MSU/xibridge#1]
Hi, I am trying to compile xibridge with `CMAKE_CXX_STANDARD=17`. Currently the compilation is failing because of a deprecated symbol referenced by a dependency in Bindy, which is detailed in [another issue](https://github.com/EPC-MSU/Bindy/issues/3).

Fortunately, the fix for this is easy. Once Bindy applies it upstream, I would recommend bumping the checked out commit of `vendor/bindy` to bring it into xibridge. Locally I have verified that xibridge compiles with patched Bindy, so there should be no functional  obstacles in implementing this.

**Comment by shampletov-no** [comment]
As was mentioned in [this issue](https://github.com/EPC-MSU/Bindy/issues/3), we cannot apply upstream fixes without breaking compatibility with our old devices :_(
